version: "1.0"
info:
  model: int-scaffold
packages:
- name: US02_Shashank_Sample2Project
  gitServerName: Shashank
  gitUrl: https://github.com/patelshashank/US02_Shashank_Sample2Project
  gitUsername: patelshashank
  gitBranch: main
services:
- serviceName: project.us02_shashank_sample2.integrations:addIntegers
  packages:
  - name: US02_Shashank_Sample2Project
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
