version: "1.0"
info:
  model: int-scaffold
packages:
- name: US02_Shashank_Sample2Project
  gitServerName: Shashank
  gitUrl: https://github.com/patelshashank/US02_Shashank_Sample2Project
  gitUsername: patelshashank
  gitBranch: main
- name: MgOrderUtil
  gitServerName: presaleseueplus_shashank
  gitUrl: https://github.com/patelshashank
  gitUsername: patelshashank
  gitBranch: master
services:
- serviceName: project.us02_shashank_sample2.integrations:addIntegers
  packages:
  - name: US02_Shashank_Sample2Project
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
- serviceName: project.us02_shashank_sample2.integrations:determineShippingDetails_WrapperSvc
  packages:
  - name: US02_Shashank_Sample2Project
    version: "1.0"
  - name: MgOrderUtil
    version: "1.0"
- serviceName: mgOrderUtil.services:determineShippingDetails
  packages:
  - name: MgOrderUtil
    version: "1.0"
- serviceName: pub.string:objectToString
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
- serviceName: pub.math:multiplyInts
  packages:
  - name: WmPublic
    version: 11.0.0.0.741
